name 'dantremblay-addontools'
version '0.1.0'
source 'git://github.com/dantremblay/puppet-module-addontools.git'
author 'dantremblay'
license 'Apache License, Version 2.0'
summary 'put a summary here'
description 'put a description here'
project_page 'https://github.com/dantremblay/puppet-module-addontools'

dependency 'puppetlabs/stdlib', '3.2.x'
